spring.application.name=Zhimdhen-POS
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/zhimdhen_db
spring.datasource.username=root
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# JWT SIGNING INFO
jwt.secret=c2RmZ2hqa2l1dHJmZ2Joaml1NzZyZGZ2YmhqdXl0cmRmZ2hqdXl0cmVhc2RmZ2hqa3dlcnR5dWlvMzQ1Njc4OQ==
jwt.access-token-expiration=3600000
jwt.refresh-token-expiration=604800000

# Cors Info
cors.originUrl=http://192.168.1.106:4200
spring.web.resources.static-locations=file:uploads/images/
